[project]
name = "pixi-econometrics"
version = "0.1.0"
description = "Pixi environment for statistical learning and econometrics"
authors = ["Niall Keleher <niall.keleher@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
# base
python = ">=3.9,<4.0"
duckdb-engine = ">=0.9.5,<0.10"
mimesis = ">=13.1.0,<13.2"
pandas = ">=2.1.4,<3.0"
polars = ">=0.20.7,<1.0"
pyarrow = ">=14.0.0,<15.1"

# data visualization
altair = ">=5.2.0,<6.0"
seaborn = ">=0.13.0,<1.0"
arviz = ">=0.17.0,<1.0"

# tables
great_tables = ">=0.1.5,<0.3"
econml = ">=0.12.0,<0.13"
linearmodels = ">=5.4,<6"
statsforecast = ">=1.7.2,<1.8"
statsmodels = ">=0.14.1,<0.15"

# machine learning
lightgbm = ">=4.2.0,<5.0"
mapie = ">=0.7.0,<1.0"
xgboost = ">=2.0.3,<2.1"
scikit-learn = ">=1.2.2,<1.5"

# causal ml
causalpy = ">=0.2.0,<1.0"
dowhy = ">=0.7.1,<1.0"

# bayesian
bambi = ">=0.13.0,<0.14"
pymc = ">=5.10.3,<5.11"

# notebooks
jupysql = ">=0.10.7,<0.11"
jupyterlab = ">=4.0.10,<4.1"
jupytext = ">=1.16.0,<1.17"

# dev
pre-commit = ">=3.6.0,<3.7"
ruff = ">=0.1.11,<0.2"

[pypi-dependencies]
stargazer = "*"
regtabletotext = "*"
binsreg = "*"
pyfixest = "*"
