[project]
name = "pixi-econometrics"
version = "0.1.0"
description = "Pixi environment for statistical learning and econometrics"
authors = ["Niall Keleher <niall.keleher@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = ">=3.9,<4.0"
altair = ">=5.2.0,<5.3"
arviz = ">=0.17.0,<0.18"
bambi = ">=0.13.0,<0.14"
causalpy = ">=0.2.0,<0.3"
csvkit = ">=1.0.7,<1.4"
dowhy = ">=0.7.1,<0.8"
duckdb-engine = ">=0.9.5,<0.10"
econml = ">=0.14.1,<0.15"
formulaic = ">=0.6.6,<1.0.0"
graphviz = ">=9.0.0,<9.1"
great_tables = ">=0.1.5,<0.2"
handcalcs = ">=1.6.5,<1.7"
ipython = ">=8.19.0,<8.20"
ipywidgets = ">=8.1.1,<8.2"
jupysql = ">=0.10.7,<0.11"
jupyterlab = ">=4.0.10,<4.1"
jupytext = ">=1.16.0,<1.17"
lightgbm = ">=4.2.0,<4.3"
linearmodels = ">=5.3,<6"
mapie = ">=0.7.0,<0.8"
matplotlib = ">=3.8.2,<3.9"
mimesis = ">=12.1.0,<12.2"
numpy = ">=1.23.5,<1.24"
openml = ">=0.12.2,<0.13"
pandas = ">=2.1.4,<2.2"
pip = ">=23.3.2,<23.4"
ploomber = ">=0.22.4,<0.23"
polars = ">=0.20.5,<0.21"
pre-commit = ">=3.6.0,<3.7"
pyarrow = ">=13.0.0,<14.0.0"
pymc = ">=5.10.3,<5.11"
scalene = ">=1.5.31.1,<1.5.32"
scikit-learn = ">=1.2.2,<1.3"
scipy = ">=1.11.4,<1.12"
seaborn = ">=0.13.0,<0.14"
statsforecast = ">=1.7.0,<1.8"
statsmodels = ">=0.14.1,<0.15"
sympy = ">=1.12,<2"
xgboost = ">=2.0.3,<2.1"
xlsx2csv = ">=0.8.1,<0.9"
watermark = ">=2.4.3,<2.5"
radian = ">=0.6.9,<0.7"
ruff = ">=0.1.11,<0.2"

[pypi-dependencies]
stargazer = ">=0.0.6"
pymarginaleffects = ">=0.0.6"
pyfixest = ">=0.15"
regtabletotext = ">=0.0.12"
binsreg = ">=2.1"
statsframe = ">=0.0.3"
